<!-- TwitterCard start -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@klapp_kamp" />
<meta name="twitter:creator" content="@klapp_kamp" />
<meta name="twitter:title" content="イベンターに幸あれ" />
<meta name="twitter:description" content="イベンターのための日程、申込スケジュール管理アプリ" />
<meta name="twitter:url" content="http://eventer.daynight.jp/" />
<meta name="twitter:image" content="http://eventer.daynight.jp/files/evesachi_tmb.jpg" />
<!-- TwitterCard end -->